// <auto-generated />
namespace WebApiRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rename_column_HeroesImages_CloudinaryUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_column_HeroesImages_CloudinaryUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "201606101051014_rename_column_HeroesImages_CloudinaryUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
